/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practiceproject;


import javax.swing.JFrame;

/**
 *
 * @author Os-10
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        
    }

    public HomePage(String education_Management_System) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sp_student = new javax.swing.JPanel();
        l_student_logo = new javax.swing.JLabel();
        bttn_student = new javax.swing.JButton();
        sp_results = new javax.swing.JPanel();
        l_results_logo = new javax.swing.JLabel();
        bttn_results = new javax.swing.JButton();
        sp_exam = new javax.swing.JPanel();
        bttn_exam = new javax.swing.JButton();
        l_classroom_logo = new javax.swing.JLabel();
        sp_cantine = new javax.swing.JPanel();
        l_cantine_logo = new javax.swing.JLabel();
        bttn_note = new javax.swing.JButton();
        sp_teachers = new javax.swing.JPanel();
        l_teacher_logo = new javax.swing.JLabel();
        bttn_teachers = new javax.swing.JButton();
        sp_admin = new javax.swing.JPanel();
        l_admin_logo = new javax.swing.JLabel();
        bttn_admin = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        menu_bar = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Education Management System");
        setBackground(new java.awt.Color(204, 255, 255));

        sp_student.setBackground(new java.awt.Color(255, 255, 255));
        sp_student.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(185, 183, 183), 3, true));

        l_student_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_student_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/student.jpg"))); // NOI18N

        bttn_student.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bttn_student.setText("Admission");
        bttn_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_studentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sp_studentLayout = new javax.swing.GroupLayout(sp_student);
        sp_student.setLayout(sp_studentLayout);
        sp_studentLayout.setHorizontalGroup(
            sp_studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bttn_student, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sp_studentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(l_student_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        sp_studentLayout.setVerticalGroup(
            sp_studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sp_studentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_student_logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttn_student, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
        );

        sp_results.setBackground(new java.awt.Color(255, 255, 255));
        sp_results.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(185, 183, 183), 3, true));

        l_results_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_results_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/result.png"))); // NOI18N

        bttn_results.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bttn_results.setText("Results");
        bttn_results.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_resultsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sp_resultsLayout = new javax.swing.GroupLayout(sp_results);
        sp_results.setLayout(sp_resultsLayout);
        sp_resultsLayout.setHorizontalGroup(
            sp_resultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sp_resultsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_results_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(bttn_results, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sp_resultsLayout.setVerticalGroup(
            sp_resultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sp_resultsLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(l_results_logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttn_results, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        sp_exam.setBackground(new java.awt.Color(255, 255, 255));
        sp_exam.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(185, 183, 183), 3, true));

        bttn_exam.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bttn_exam.setText("Quiz");
        bttn_exam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_examActionPerformed(evt);
            }
        });

        l_classroom_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/classroom.png"))); // NOI18N

        javax.swing.GroupLayout sp_examLayout = new javax.swing.GroupLayout(sp_exam);
        sp_exam.setLayout(sp_examLayout);
        sp_examLayout.setHorizontalGroup(
            sp_examLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bttn_exam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sp_examLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(l_classroom_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        sp_examLayout.setVerticalGroup(
            sp_examLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sp_examLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(l_classroom_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttn_exam, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        sp_cantine.setBackground(new java.awt.Color(255, 255, 255));
        sp_cantine.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(185, 183, 183), 3, true));

        l_cantine_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/email.png"))); // NOI18N

        bttn_note.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bttn_note.setText("Send Record");
        bttn_note.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_noteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sp_cantineLayout = new javax.swing.GroupLayout(sp_cantine);
        sp_cantine.setLayout(sp_cantineLayout);
        sp_cantineLayout.setHorizontalGroup(
            sp_cantineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bttn_note, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sp_cantineLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(l_cantine_logo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sp_cantineLayout.setVerticalGroup(
            sp_cantineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sp_cantineLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(l_cantine_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttn_note, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        sp_teachers.setBackground(new java.awt.Color(255, 255, 255));
        sp_teachers.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(185, 183, 183), 3, true));

        l_teacher_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/teacher.png"))); // NOI18N

        bttn_teachers.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bttn_teachers.setText("Teachers");
        bttn_teachers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_teachersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sp_teachersLayout = new javax.swing.GroupLayout(sp_teachers);
        sp_teachers.setLayout(sp_teachersLayout);
        sp_teachersLayout.setHorizontalGroup(
            sp_teachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bttn_teachers, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
            .addGroup(sp_teachersLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(l_teacher_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        sp_teachersLayout.setVerticalGroup(
            sp_teachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sp_teachersLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(l_teacher_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttn_teachers, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        sp_admin.setBackground(new java.awt.Color(255, 255, 255));
        sp_admin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(185, 183, 183), 3, true));

        l_admin_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin.jpg"))); // NOI18N

        bttn_admin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bttn_admin.setText("Admin");
        bttn_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_adminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sp_adminLayout = new javax.swing.GroupLayout(sp_admin);
        sp_admin.setLayout(sp_adminLayout);
        sp_adminLayout.setHorizontalGroup(
            sp_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sp_adminLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(l_admin_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(bttn_admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sp_adminLayout.setVerticalGroup(
            sp_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sp_adminLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(l_admin_logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttn_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("School management System");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Dhaka, Bangladesh.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        setJMenuBar(menu_bar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sp_results, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_student, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sp_exam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_teachers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sp_cantine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sp_admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sp_exam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_cantine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_student, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sp_teachers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_results, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_admin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bttn_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_studentActionPerformed
        // TODO add your handling code here:
        AgeCheck ac = new AgeCheck();
        ac.setVisible(true);
        ac.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_bttn_studentActionPerformed

    private void bttn_resultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_resultsActionPerformed
        // TODO add your handling code here:
        StudentResult sr = new StudentResult();
        sr.setVisible(true);
        sr.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_bttn_resultsActionPerformed

    private void bttn_noteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_noteActionPerformed
        // TODO add your handling code here:
       EmailSending es = new EmailSending();
       es.setVisible(true);
       es.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_bttn_noteActionPerformed

    private void bttn_examActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_examActionPerformed
        // TODO add your handling code here:
    OnlineTest test = new OnlineTest("Online Test Of General Knowledge"); 
    test.setVisible(true);
    test.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       
        
    }//GEN-LAST:event_bttn_examActionPerformed

    private void bttn_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_adminActionPerformed
        // TODO add your handling code here:
        FindResult result = new FindResult();
        result.setVisible(true);
        result.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_bttn_adminActionPerformed

    private void bttn_teachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_teachersActionPerformed
        // TODO add your handling code here:
        TeacherList teacher = new TeacherList();
        teacher.setVisible(true);
        teacher.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_bttn_teachersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        // new OnlineTest("Online Test Of General Knowledge");  
        
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
                
            }
        });
       
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_admin;
    private javax.swing.JButton bttn_exam;
    private javax.swing.JButton bttn_note;
    private javax.swing.JButton bttn_results;
    private javax.swing.JButton bttn_student;
    private javax.swing.JButton bttn_teachers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l_admin_logo;
    private javax.swing.JLabel l_cantine_logo;
    private javax.swing.JLabel l_classroom_logo;
    private javax.swing.JLabel l_results_logo;
    private javax.swing.JLabel l_student_logo;
    private javax.swing.JLabel l_teacher_logo;
    private javax.swing.JMenuBar menu_bar;
    private javax.swing.JPanel sp_admin;
    private javax.swing.JPanel sp_cantine;
    private javax.swing.JPanel sp_exam;
    private javax.swing.JPanel sp_results;
    private javax.swing.JPanel sp_student;
    private javax.swing.JPanel sp_teachers;
    // End of variables declaration//GEN-END:variables
}
