/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practiceproject;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Os-10
 */
public class StudentResult extends javax.swing.JFrame {
    JDBCConnection jdbc = new JDBCConnection();
    PreparedStatement pst;
    Statement st;
    ResultSet rs;
    /**
     * Creates new form StudentResult
     */
    public StudentResult() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new javax.swing.JPanel();
        left_panel = new javax.swing.JPanel();
        l_roll = new javax.swing.JLabel();
        l_name = new javax.swing.JLabel();
        l_class = new javax.swing.JLabel();
        l_bangla = new javax.swing.JLabel();
        l_english = new javax.swing.JLabel();
        l_math = new javax.swing.JLabel();
        l_science = new javax.swing.JLabel();
        st_id = new javax.swing.JTextField();
        st_name = new javax.swing.JTextField();
        st_class = new javax.swing.JTextField();
        ban = new javax.swing.JTextField();
        eng = new javax.swing.JTextField();
        mat = new javax.swing.JTextField();
        sci = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        l_totalmark = new javax.swing.JLabel();
        l_average = new javax.swing.JLabel();
        l_grade = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        avg = new javax.swing.JTextField();
        grd = new javax.swing.JTextField();
        l_ro = new javax.swing.JLabel();
        bttn_submit = new javax.swing.JButton();
        bttn_exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        main_panel.setBackground(new java.awt.Color(240, 235, 243));
        main_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(186, 195, 195), 3, true), "Result Of Students", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(0, 0, 255))); // NOI18N

        left_panel.setBackground(new java.awt.Color(224, 221, 221));
        left_panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        l_roll.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l_roll.setText("ID");

        l_name.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l_name.setText("Name");

        l_class.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l_class.setText("Class");

        l_bangla.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l_bangla.setText("Bangla");

        l_english.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l_english.setText("English");

        l_math.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l_math.setText("Mathemarics");

        l_science.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l_science.setText("Science");

        st_id.setBackground(new java.awt.Color(240, 235, 243));
        st_id.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        st_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st_idActionPerformed(evt);
            }
        });

        st_name.setBackground(new java.awt.Color(240, 235, 243));
        st_name.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        st_class.setBackground(new java.awt.Color(240, 235, 243));
        st_class.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        ban.setBackground(new java.awt.Color(240, 235, 243));
        ban.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        eng.setBackground(new java.awt.Color(240, 235, 243));
        eng.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        mat.setBackground(new java.awt.Color(240, 235, 243));
        mat.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        sci.setBackground(new java.awt.Color(240, 235, 243));
        sci.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        javax.swing.GroupLayout left_panelLayout = new javax.swing.GroupLayout(left_panel);
        left_panel.setLayout(left_panelLayout);
        left_panelLayout.setHorizontalGroup(
            left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(left_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(left_panelLayout.createSequentialGroup()
                        .addComponent(l_science)
                        .addGap(74, 74, 74)
                        .addComponent(sci))
                    .addGroup(left_panelLayout.createSequentialGroup()
                        .addComponent(l_math)
                        .addGap(30, 30, 30)
                        .addComponent(mat))
                    .addGroup(left_panelLayout.createSequentialGroup()
                        .addGroup(left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(l_bangla)
                            .addComponent(l_english))
                        .addGap(74, 74, 74)
                        .addGroup(left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eng)
                            .addComponent(ban)))
                    .addGroup(left_panelLayout.createSequentialGroup()
                        .addComponent(l_class)
                        .addGap(90, 90, 90)
                        .addComponent(st_class))
                    .addGroup(left_panelLayout.createSequentialGroup()
                        .addComponent(l_name)
                        .addGap(86, 86, 86)
                        .addComponent(st_name))
                    .addGroup(left_panelLayout.createSequentialGroup()
                        .addComponent(l_roll)
                        .addGap(111, 111, 111)
                        .addComponent(st_id, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)))
                .addContainerGap())
        );
        left_panelLayout.setVerticalGroup(
            left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(left_panelLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_roll, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(st_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_name, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(st_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_class, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(st_class, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_bangla, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ban, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_english, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(eng, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_math, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_science))
                .addGap(20, 20, 20))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        l_totalmark.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l_totalmark.setText("TotalMarks");

        l_average.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l_average.setText("Average");

        l_grade.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l_grade.setText("Grade");

        total.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        avg.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        grd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        l_ro.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        l_ro.setText("Results Obtained");

        bttn_submit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bttn_submit.setText("Submit");
        bttn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_submitActionPerformed(evt);
            }
        });

        bttn_exit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bttn_exit.setText("Exit");
        bttn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(l_grade)
                                .addGap(53, 53, 53)
                                .addComponent(grd))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(l_average)
                                .addGap(38, 38, 38)
                                .addComponent(avg))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(l_totalmark)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(total))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(l_ro)
                        .addGap(0, 60, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bttn_submit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bttn_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_ro)
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(l_totalmark)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_average)
                    .addComponent(avg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_grade)
                    .addComponent(grd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(bttn_submit)
                .addGap(35, 35, 35)
                .addComponent(bttn_exit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout main_panelLayout = new javax.swing.GroupLayout(main_panel);
        main_panel.setLayout(main_panelLayout);
        main_panelLayout.setHorizontalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addComponent(left_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        main_panelLayout.setVerticalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(left_panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bttn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_submitActionPerformed
        // bttn submit
        
        double a, b, c, d, tot, av;
        String gr;
        a = Double.parseDouble(ban.getText());
        b = Double.parseDouble(eng.getText());
        c = Double.parseDouble(mat.getText());
        d = Double.parseDouble(sci.getText());
        tot = a + b + c + d;
        av =  tot/4; 
        // now grade
        if (av <= 32) {
            gr = "F";    
        } else if(av > 32 && av <= 39){
            gr = "D";         
        }else if (av >= 40 && av <= 49) {
            gr = "C";         
        }else if (av >= 50 && av <= 59) {
            gr = "B";          
        }else if (av >= 60 && av <= 69) {
            gr = "A-";          
        }else if (av >=70 && av <= 79) {
            gr = "A";          
        }else if (av >=80 && av <= 100) {
            gr = "A+";          
        }else{
           gr = "Invalid?";
          
        }
        
        total.setText(Double.toString(tot));
        grd.setText(gr);
        avg.setText(Double.toString(av));
        
        
        
        String id = st_id.getText();
        String name = st_name.getText();
        String clas = st_class.getText();
        String bangla = ban.getText();
        String english = eng.getText();
        String math = mat.getText();
        String science = sci.getText();
        String totalmark = total.getText();
        String average = avg.getText();
        String grade = grd.getText();
            // insert database
        try {
           
            pst = jdbc.getConnection().prepareStatement("insert into result(id,name,class,bangla,english,math,science,totalmark,average,grade) values(?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1, id);
            pst.setString(2, name);
            pst.setString(3, clas);
            pst.setString(4, bangla);
            pst.setString(5, english);
            pst.setString(6, math);
            pst.setString(7, science);
            pst.setString(8, totalmark);
            pst.setString(9, average);
            pst.setString(10, grade);
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "insert data successfully");
        } catch (SQLException ex) {
            System.out.println("Error sql exception");
            
        }
        
    }//GEN-LAST:event_bttn_submitActionPerformed

    private void bttn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_exitActionPerformed
        // bttn Eixit
        System.exit(0);
    }//GEN-LAST:event_bttn_exitActionPerformed

    private void st_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_st_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentResult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField avg;
    private javax.swing.JTextField ban;
    private javax.swing.JButton bttn_exit;
    private javax.swing.JButton bttn_submit;
    private javax.swing.JTextField eng;
    private javax.swing.JTextField grd;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel l_average;
    private javax.swing.JLabel l_bangla;
    private javax.swing.JLabel l_class;
    private javax.swing.JLabel l_english;
    private javax.swing.JLabel l_grade;
    private javax.swing.JLabel l_math;
    private javax.swing.JLabel l_name;
    private javax.swing.JLabel l_ro;
    private javax.swing.JLabel l_roll;
    private javax.swing.JLabel l_science;
    private javax.swing.JLabel l_totalmark;
    private javax.swing.JPanel left_panel;
    private javax.swing.JPanel main_panel;
    private javax.swing.JTextField mat;
    private javax.swing.JTextField sci;
    private javax.swing.JTextField st_class;
    private javax.swing.JTextField st_id;
    private javax.swing.JTextField st_name;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
