/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practiceproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Os-10
 */
public class Student extends javax.swing.JFrame {
    
    JDBCConnection jdbc = new JDBCConnection();
    PreparedStatement pst;
    Statement st;
    ResultSet rs;
   
    /**
     * Creates new form Student
     */
    public Student() {
        initComponents();
       

        
    }
    void sentStudent(String name){
    st_name.setText(name);
  
   
    }
    

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        m_name1 = new javax.swing.JTextField();
        form_panel = new javax.swing.JPanel();
        l_stname = new javax.swing.JLabel();
        l_fname = new javax.swing.JLabel();
        l_mname = new javax.swing.JLabel();
        l_class = new javax.swing.JLabel();
        l_gender = new javax.swing.JLabel();
        l_religion = new javax.swing.JLabel();
        l_address = new javax.swing.JLabel();
        l_bloodgroup = new javax.swing.JLabel();
        l_dob = new javax.swing.JLabel();
        st_name = new javax.swing.JTextField();
        f_name = new javax.swing.JTextField();
        m_name = new javax.swing.JTextField();
        classes = new javax.swing.JTextField();
        t_dob = new javax.swing.JTextField();
        r_boy = new javax.swing.JRadioButton();
        r_girl = new javax.swing.JRadioButton();
        reli = new javax.swing.JComboBox<>();
        blood = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        addre = new javax.swing.JTextArea();
        r_other = new javax.swing.JRadioButton();
        bttn_save = new javax.swing.JButton();
        bttn_clear = new javax.swing.JButton();
        l_address1 = new javax.swing.JLabel();
        t_mail = new javax.swing.JTextField();

        m_name1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        m_name1.setToolTipText("Enter Mother's name");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        form_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(51, 51, 255))); // NOI18N

        l_stname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        l_stname.setText("Name");

        l_fname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        l_fname.setText("Father");

        l_mname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        l_mname.setText("Mother");

        l_class.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        l_class.setText("Class");

        l_gender.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        l_gender.setText("Gender");

        l_religion.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        l_religion.setText("Religion");

        l_address.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        l_address.setText("Address");

        l_bloodgroup.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        l_bloodgroup.setText("BloodGroup");

        l_dob.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        l_dob.setText("Birthday");

        st_name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        st_name.setToolTipText("Enter Student name");

        f_name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        f_name.setToolTipText("Enter Father's name");

        m_name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        m_name.setToolTipText("Enter Mother's name");

        classes.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        classes.setToolTipText("Enter Class name");

        t_dob.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        t_dob.setToolTipText("Enter Date of Birth");

        buttonGroup1.add(r_boy);
        r_boy.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        r_boy.setText("Boy");

        buttonGroup1.add(r_girl);
        r_girl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        r_girl.setText("Girl");

        reli.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        reli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selected", "Islam", "Hindu", "Khristan", "Bodtho", "Others" }));

        blood.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        blood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selected", "O+", "A+", "B+", "AB+", "O-", "A-", "AB-" }));

        addre.setColumns(20);
        addre.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        addre.setRows(2);
        addre.setTabSize(2);
        jScrollPane1.setViewportView(addre);

        buttonGroup1.add(r_other);
        r_other.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        r_other.setText("Other");

        bttn_save.setBackground(new java.awt.Color(51, 255, 51));
        bttn_save.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bttn_save.setText("Save");
        bttn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_saveActionPerformed(evt);
            }
        });

        bttn_clear.setBackground(new java.awt.Color(255, 51, 51));
        bttn_clear.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bttn_clear.setText("Clear");
        bttn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_clearActionPerformed(evt);
            }
        });

        l_address1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        l_address1.setText("Mail");

        t_mail.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        t_mail.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        t_mail.setText("@gmail.com");
        t_mail.setToolTipText("Enter Mail Address");

        javax.swing.GroupLayout form_panelLayout = new javax.swing.GroupLayout(form_panel);
        form_panel.setLayout(form_panelLayout);
        form_panelLayout.setHorizontalGroup(
            form_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(form_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(form_panelLayout.createSequentialGroup()
                        .addGroup(form_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_dob)
                            .addComponent(l_religion)
                            .addComponent(l_bloodgroup)
                            .addComponent(l_gender)
                            .addComponent(bttn_clear)
                            .addComponent(l_class)
                            .addComponent(l_address))
                        .addGap(93, 93, 93)
                        .addGroup(form_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(classes)
                            .addComponent(t_dob)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, form_panelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(bttn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(form_panelLayout.createSequentialGroup()
                                .addComponent(r_boy)
                                .addGap(50, 50, 50)
                                .addComponent(r_girl)
                                .addGap(62, 62, 62)
                                .addComponent(r_other)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(reli, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(blood, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(form_panelLayout.createSequentialGroup()
                        .addGroup(form_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_fname)
                            .addComponent(l_mname))
                        .addGap(120, 120, 120)
                        .addGroup(form_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(f_name)
                            .addComponent(m_name)))
                    .addGroup(form_panelLayout.createSequentialGroup()
                        .addComponent(l_stname)
                        .addGap(130, 130, 130)
                        .addComponent(st_name))
                    .addGroup(form_panelLayout.createSequentialGroup()
                        .addComponent(l_address1)
                        .addGap(138, 138, 138)
                        .addComponent(t_mail)))
                .addContainerGap())
        );
        form_panelLayout.setVerticalGroup(
            form_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(form_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_stname)
                    .addComponent(st_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(form_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_fname)
                    .addComponent(f_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(form_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_mname)
                    .addComponent(m_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(form_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_class)
                    .addComponent(classes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(form_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_dob)
                    .addComponent(t_dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(form_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_gender)
                    .addComponent(r_boy)
                    .addComponent(r_girl)
                    .addComponent(r_other))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(form_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_religion)
                    .addComponent(reli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(form_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_bloodgroup)
                    .addComponent(blood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(form_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_address1)
                    .addComponent(t_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(form_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_address))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(form_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttn_clear)
                    .addComponent(bttn_save))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(form_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(form_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bttn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_clearActionPerformed
        // clear bttn
       
        st_name.setText("");
        f_name.setText("");
        m_name.setText("");
        classes.setText("");
        t_dob.setText("");
        addre.setText("");
       
    }//GEN-LAST:event_bttn_clearActionPerformed

    private void bttn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_saveActionPerformed
        // save bttn
        
        String name = st_name.getText();
        String fname = f_name.getText();       
        String clas = classes.getText();
        String dob = t_dob.getText();    
        String address = addre.getText();
        
        
        try {
            pst = jdbc.getConnection().prepareStatement("insert into student(name,f_name,class,dob,address) values(?,?,?,?,?)");
            pst.setString(1, name);
            pst.setString(2, fname);
            pst.setString(3, clas);
            pst.setString(4, dob);
            pst.setString(5, address);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "insert successfull");
            
            
            
        } catch (SQLException ex) {       
            
        }
        
    }//GEN-LAST:event_bttn_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addre;
    private javax.swing.JComboBox<String> blood;
    private javax.swing.JButton bttn_clear;
    private javax.swing.JButton bttn_save;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField classes;
    private javax.swing.JTextField f_name;
    private javax.swing.JPanel form_panel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l_address;
    private javax.swing.JLabel l_address1;
    private javax.swing.JLabel l_bloodgroup;
    private javax.swing.JLabel l_class;
    private javax.swing.JLabel l_dob;
    private javax.swing.JLabel l_fname;
    private javax.swing.JLabel l_gender;
    private javax.swing.JLabel l_mname;
    private javax.swing.JLabel l_religion;
    private javax.swing.JLabel l_stname;
    private javax.swing.JTextField m_name;
    private javax.swing.JTextField m_name1;
    private javax.swing.JRadioButton r_boy;
    private javax.swing.JRadioButton r_girl;
    private javax.swing.JRadioButton r_other;
    private javax.swing.JComboBox<String> reli;
    private javax.swing.JTextField st_name;
    private javax.swing.JTextField t_dob;
    private javax.swing.JTextField t_mail;
    // End of variables declaration//GEN-END:variables
}
